added Mixins for last viewed products
Python-hobbits/Awesome_ecommerce pull request #43
Opened 2023-10-31 14:33 UTC by volodin28

2023-10-31 15:13 UTC, egorvavilov requested changes

2023-10-31 15:13 UTC, egorvavilov commented on src/apps/inventory/mixins.py
> +        products = Product.objects.in_bulk(map(int, last_viewed_products_ids))
Nice

2023-10-31 15:13 UTC, egorvavilov commented on src/apps/inventory/mixins.py
> +            (int(product_id), products[int(product_id)]) for product_id in last_viewed_products_ids
Why so complicated? You already extracted products and mapped them to ids with in_bulk query

2023-10-31 15:13 UTC, egorvavilov commented on src/apps/inventory/mixins.py
> +        view_count = redis.incr(f"{user_key}:counter")
Can we simply dump datetime in seconds smth like "123214234525" ?
Set will guarantee uniquness and timecode will ensure lastviewed logic

2023-10-31 15:13 UTC, egorvavilov commented on src/apps/inventory/mixins.py
> +        redis.zadd(user_key, {product.id: view_count})
you don't need to add it
because you already incr your value

2023-10-31 15:13 UTC, egorvavilov commented on src/apps/inventory/mixins.py
> +        view_count = redis.incr(f"{user_key}:counter")
wait, now I don't get it at all

2023-11-01 06:19 UTC, GrazhdanochkaMariya commented
We started adding some documentation to the project and your complex task definitely needs in it

2023-11-02 12:17 UTC, egorvavilov approved these changes

2023-11-02 12:17 UTC, merged